/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package song;

import javax.swing.*;
import java.awt.*;
import java.io.File;

/**
 *
 * @author Nathan
 */
public class AñadirMusica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AñadirMusica.class.getName());
    private static PlayList playList = new PlayList(100); // Instancia estática para mantener las canciones
    private ImageIcon imagenSeleccionada = null;

    /**
     * Creates new form AñadirMusica
     */
    public AñadirMusica() {
        initComponents();
        setSize(525, 515);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButtonSeleccionarImagen = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 120, 50);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 4, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 80, 250, 50);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Código");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 160, 120, 50);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 240, 120, 50);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 4, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 160, 250, 50);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 4, true));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 240, 250, 50);

        jButtonSeleccionarImagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSeleccionarImagen.setText("Seleccionar Imagen");
        jButtonSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccionarImagen);
        jButtonSeleccionarImagen.setBounds(20, 320, 180, 40);

        jLabelImagen.setBackground(new java.awt.Color(204, 204, 204));
        jLabelImagen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setText("Sin imagen");
        jLabelImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 2, true));
        getContentPane().add(jLabelImagen);
        jLabelImagen.setBounds(230, 320, 100, 100);

        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar);
        jButtonAgregar.setBounds(360, 330, 120, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 390, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/elegir.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 530, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Archivos de imagen", "jpg", "jpeg", "png", "gif", "bmp"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagenSeleccionada = new ImageIcon(selectedFile.getAbsolutePath());
            
            // Escalar la imagen para que se vea bien en el label
            Image img = imagenSeleccionada.getImage();
            Image scaledImg = img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImg);
            
            jLabelImagen.setIcon(scaledIcon);
            jLabelImagen.setText(""); // Quitar el texto "Sin imagen"
        }
    }//GEN-LAST:event_jButtonSeleccionarImagenActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // Obtener datos de los campos
        String codigoText = jTextField2.getText();
        String nombreText = jTextField1.getText();
        String precioText = jTextField3.getText();
        
        // Validar campos usando la clase Ingreso
        if (!Ingreso.validarCamposCancion(codigoText, nombreText, precioText)) {
            // Mostrar errores específicos
            if (!Ingreso.validarTextoNoVacio(codigoText) || 
                !Ingreso.validarTextoNoVacio(nombreText) || 
                !Ingreso.validarTextoNoVacio(precioText)) {
                Ingreso.mostrarErrorCamposVacios();
                return;
            }
            
            // Verificar errores específicos
            if (Ingreso.obtenerCodigo(codigoText) == -1) {
                Ingreso.mostrarErrorCodigoInvalido();
                return;
            }
            
            if (Ingreso.obtenerNombre(nombreText) == null) {
                Ingreso.mostrarErrorNombreInvalido();
                return;
            }
            
            if (Ingreso.obtenerPrecio(precioText) == -1.0) {
                Ingreso.mostrarErrorPrecioInvalido();
                return;
            }
            
            return;
        }
        
        // Obtener datos validados
        int codigo = Ingreso.obtenerCodigo(codigoText);
        String nombre = Ingreso.obtenerNombre(nombreText);
        double precio = Ingreso.obtenerPrecio(precioText);
        
        // Intentar agregar la canción
        boolean agregado = playList.addSong(codigo, nombre, precio, imagenSeleccionada);
        
        if (agregado) {
            Ingreso.mostrarExitoCancionAgregada();
            limpiarCampos();
        } else {
            Ingreso.mostrarErrorCancionNoAgregada();
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Volver al menú principal
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void limpiarCampos() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jLabelImagen.setIcon(null);
        jLabelImagen.setText("Sin imagen");
        imagenSeleccionada = null;
    }
    
    // Método estático para obtener la instancia de PlayList
    public static PlayList getPlayList() {
        return playList;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AñadirMusica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonSeleccionarImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
